NDEBUG    := t
MPI       := t
OMP       :=
PROF      :=
COMP      := gfortran
TILING    :=

HYPRE  := 

# define the location of the MAESTRO root directory
VARDEN_TOP_DIR := ../..
FBOXLIB_HOME := ../../../FBoxLib

# include the MAESTRO build stuff
include $(VARDEN_TOP_DIR)/GVarden.mak
